### ISSUE TITLE
😓😓😓作者你就不能上传压缩包么？

### ISSUE THREAD

**Issue by welkin159** [Arthurzhangsheng/echomimic-all-in-one-package#2]
作者你就不能上传压缩包么？一体包是完整文件没错，但是就算开了百度云盘会员下载文件个数也是只能同时5个啊，20万个文件，每秒5个也要下载11小时😓😓😓

**Comment by Arthurzhangsheng** [comment]
好吧，晚上传一个
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月26日(星期一) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [Arthurzhangsheng/echomimic-all-in-one-package] 😓😓😓作者你就不能上传压缩包么？ (Issue #2)














 
作者你就不能上传压缩包么？一体包是完整文件没错，但是就算开了百度云盘会员下载文件个数也是只能同时5个啊，20万个文件，每秒5个也要下载11小时😓😓😓

**Comment by Arthurzhangsheng** [comment]
https://pan.baidu.com/s/1JTBQs_PVzhWDZMJ70vgl1g?pwd=mxvx

**Comment by welkin159** [comment]
感谢大佬QAQ

**Comment by welkin159** [comment]
感谢大佬QAQ
